[versions]
gradlePlugin = "7.4.2"
kotlin = "1.8.0"
googleServices = "4.3.15"
playServicesAds = "21.5.0"
firebaseCrashylytics = "2.9.4"

coreKTX = "1.9.0"
appCompat = "1.6.1"
material = "1.8.0"
constraintLayout = "2.1.4"
activityKTX = "1.6.1"
lifecycle = "2.2.0"

textRecognition = "18.0.2"
languageID = "17.0.4"

retrofit = "2.9.0"
okHttp = "4.10.0"
coroutines = "1.6.4"
hawk = "2.0.1"
timber = "5.0.1"
koin = "3.3.3"

firebase = "31.3.0"

imageCropper = "4.5.0"
balloon = "1.5.2"
lottie = "3.4.0"

jUnit = "4.13.2"
jUnitExt = "1.1.5"
espresso = "3.5.1"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKTX" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKTX" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }

text-recognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "textRecognition" }
language-id = { module = "com.google.mlkit:language-id", version.ref = "languageID" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
hawk = { module = "com.orhanobut:hawk", version.ref = "hawk" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "imageCropper" }
balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

junit = { module = "junit:junit", version.ref = "jUnit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "jUnitExt" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
retrofit = ["retrofit", "retrofit-converter-gson"]
coroutines = ["coroutines-android", "coroutines-android"]
koin = ["koin-core", "koin-android"]
firebase = ["firebase-analytics-ktx", "firebase-crashlytics-ktx"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashylytics" }