name: Release CI

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Version name'
        required: true
        default: 'v1.0.0'
        type: string
      track:
        description: 'Track'
        required: true
        default: 'internal'
        type: string
      status:
        description: 'Status'
        required: true
        default: 'draft'
        type: string

env:
  CHAT_GPT_KEY: ${{ secrets.CHAT_GPT_KEY }}
  ADMOB_APP_ID: ${{ secrets.ADMOB_APP_ID }}
  ADMOB_INTERSTITIAL_ID: ${{ secrets.ADMOB_INTERSTITIAL_ID }}
  FIREBASE_GOOGLE_SERVICES: ${{ secrets.FIREBASE_GOOGLE_SERVICES }}
  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

jobs:
  create-tag:
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.track == 'production' }}

    steps:
      - name: GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.tagname }}
          prerelease: false

  google-play-release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          chmod +x .github/set-key.sh
          .github/set-key.sh
        shell: bash

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
         distribution: zulu
         java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew bundleRelease

      - name: Google Play Release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.lingshot.languagelearn
          releaseFiles: ./app/build/outputs/bundle/release/*.aab
          status: ${{ github.event.inputs.status }}
          track: ${{ github.event.inputs.track }}
